---
title: "01-dataframesprueba"
author: "Gabriel Dávila"
date: "2/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Data frame de Iris

```{r}
df1 = iris
df1
#head(df1, 5)
#tail(df1, 5)
#names(df1)
#str(df1)
names(df1) # = colnames(df1)
rownames(df1)
dimnames(df1)


dim(df1)

df1$Petal.Length[1:10]
df1$Species[1:10]
```



# Data frame de Orange
```{r}
#df2 = Orange
#df2
#str(df2)
#head(df2,4)
#tail(df2,4)

dataOrange = Orange
dataOrange[c(10:12),]
dataOrange[c(2,17),c(1,3)]
dataOrange[2,3]
dataOrange[dataOrange$circumference <= 50,]
```


## Acceso al DF

```{r}
df1[1:10,]
df1[1:10,2:4]
df1[df1$Species == "setosa" & df1$Sepal.Width > 4,]
df1[df1$Species == "setosa" & df1$Sepal.Width > 4,][c(1,3),c(2,5)]
```



## Ejercicio Lección 88

```{r}

# Ambos datasets tienen missing values "?" de acuerdo con repositorio de ML

#df4 = read.table("../../data/mydata/arrhythmia.data", sep = ",", header = FALSE, dec = ".")
#str(df4)

#write.table(df4, file = "../../data/mydata/1int.txt", sep = ",", dec = ".")

#df5 = read.table("../../data/mydata/imports-85.data", sep = ",", dec = ".", header = FALSE)
#write.table(df5, "../../data/mydata/2int.csv", sep = ",", dec = ".")

#df6 = read.csv("../../data/mydata/2int.csv")
#df6
```

## Ejercicio Lección 89

```{r}
# 15 observaciones para c/ variable

#gender
gen = c("male","female","non-binary","female","male","non-binary","female","male","female","male","male","male","female","female","female")
#age
age = c(round(runif(15, 15, 35)))
#number of siblings
sib = c(0,0,0,0,0,1,1,1,1,1,2,2,2,2,2)
df7 = data.frame(gen, age, sib, stringsAsFactors = TRUE)
str(df7)
row.names(df7) = c("P1","P2","P3","P4","P5","P6","P7","P8","P9","P10","P11","P12","P13","P14","P15")
df7
```


